global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs-backend'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['csarena-alb-330901287.ap-northeast-2.elb.amazonaws.com']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
